name: Pull request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1 # v1.146.0
      with:
        bundler-cache: true
    - name: Lint
      run: bundle exec standardrb --format github
    - name: Test
      run: bundle exec rspec --format documentation
